[alias]
r01 = "run -p module-01-intro"
c01 = "check -p module-01-intro"

c02 = "check -p module-02-routing"
r02 = "run -p module-02-routing"

c03 = "check -p module-03-extractors"
r03 = "run -p module-03-extractors"

c04 = "check -p module-04-responses"
r04 = "run -p module-04-responses"

c05 = "check -p module-05-state"
r05 = "run -p module-05-state"
